# Generated by Django 5.2.6 on 2025-09-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('tiket', 'Tiket'), ('aksesoris', 'Aksesoris'), ('makanan', 'Makanan'), ('minuman', 'Minuman'), ('dll', 'DLL')], default='dll', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
