# Generated by Django 5.2.6 on 2025-10-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
