# Generated by Django 5.2.6 on 2025-09-16 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_stock_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
